version: "3.9"
services:
  redis:
    image: redis:8.2.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ".:/data"

  wire:
    build:
      context: tools/di
      dockerfile: Dockerfile
    working_dir: /worker
    volumes:
      - .:/worker
    command: ["/worker/tools/di/entrypoint.sh"]
